resources: !include resources.yaml

title: Home
views:
    - !include 00_home_view.yaml
    - !include 20_lights_view.yaml
    - !include 25_temp_view.yaml
    - !include 30_automations.yaml
    - !include 80_develop.yaml
    - !include everything.yaml
   # - !include 99-test.yaml