homeassistant:
  name: !secret my_home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 0
  unit_system: metric
  time_zone: !secret time_zone

  # Customization file
  customize: !include_dir_merge_named customize/
  customize_glob: !include_dir_merge_named customize_glob/
  packages: !include_dir_named packages

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes/

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:
  ignore:
    - apple_tv

lovelace:
  mode: yaml

#system health
system_health:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

recorder:
  purge_keep_days: 3
  #purge_days: 2
  exclude:
    domains:
      - automation
      - script
      - input_select
      - input_boolean
      - group

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# IOS
ios: !include ios.yaml

# Apple_tv
apple_tv: !include apple_tv.yaml

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

# Cloud
cloud:

mobile_app:

notify:
  - name: pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_key

logger:
  default: info
  logs:
    homeassistant.components.device_tracker: warn
    homeassistant.components.sensor: warn
    homeassistant.components.sensor.scrape: info
    homeassistant.component.media_player: info
    homeassistant.components.unifi: error
    pydeconz: error
    homeassistant.components.deconz: error
    homeassistant.components.lock: error
    homeassistant.components.automation: error
    homeassistant.components.verisure: error

#homekit:
#  filter:
#    include_domains:
#      - light
#      - media_player

influxdb:
  host: !secret influx_host
  port: !secret influx_port
  database: !secret influx_db
  username: !secret influx_user
  password: !secret influx_pass
  max_retries: 3
  default_measurement: state

# Verisure
verisure:
  username: !secret verisure_username
  password: !secret verisure_password
  default_lock_code: !secret verisure_code
  alarm: 0
  hygrometers: 0
  smartplugs: 0
  thermometers: 0
  mouse: 0
  door_window: 0

volvooncall:
  username: !secret volvo_username
  password: !secret volvo_password

# climate:
#   - platform: adax
#     account_id: !secret adax_account_id
#     password: !secret adax_password

#device_tracker: !include device_tracker.yaml

# mikrotik:
# - name: Mikrotik
#   host: !secret mikrotik_host
#   username: !secret mikrotik_user
#   password: !secret mikrotik_pass
#   verify_ssl: false
#   port: 8728
#   arp_ping: true
#   force_dhcp: true
#   detection_time: 60


binary_sensor:
  - platform: workday
    country: SE
    workdays: [mon, tue, wed, thu, fri]
    excludes: [sat, sun, holiday]

sensor: !include_dir_merge_list sensors/
group: !include_dir_merge_named groups/
automation: !include_dir_merge_list automations/
input_number: !include input/number.yaml
script: !include_dir_merge_list scripts/
light: !include_dir_merge_list lights/
#panel_iframe: !include panel_iframe.yaml

#speedtestdotnet:
#  server_id: 21028
#  scan_interval:
#    hours: 8

shell_command:
  lovelace_gen: "python /config/commands/lovelace-gen.py > /config/lovelace-gen.log"
  firewall_kids_stop: "sh /config/commands/firewall-rule.sh firewall enable 12"
  firewall_kids_start: "sh /config/commands/firewall-rule.sh firewall disable 12"
  firewall_stop: "sh /config/commands/firewall-rule.sh firewall enable 13"
  firewall_start: "sh /config/commands/firewall-rule.sh firewall disable 13"
