- platform: group
  name: Kitchen_lights
  entities:
    - light.dimmable_light_10
    - light.dimmable_light_11


- platform: group
  name: Allrum_lights
  entities:
    - light.dimmable_light_14
    - light.dimmable_light_15

- platform: group
  name: Livingroom_lights
  entities:
    - light.color_light_18
    - light.color_light_19
    - light.color_light_20
    - light.color_temperature_light_21
