- platform: rest
  name: temp_groventre
  resource: !secret aqara_groventre
  value_template: '{{ value_json.config.temperature |  multiply(0.01) | round(1) }}'

- platform: rest
  name: temp_garage
  resource: !secret aqara_garage
  value_template: '{{ value_json.config.temperature |  multiply(0.01) | round(1) }}'