- platform: template
  sensors:
    other_lights:
      friendly_name: 'Lampor släcka övrigt'
      value_template: >-
        {% if states.input_number.other_lights_stop_hour.state|round(0)|string|length == 1 %} {% set time = 0 %} {% endif %}
        {% set time = time|string + states.input_number.other_lights_stop_hour.state|round(0)|string + ':' %}
        {% if states.input_number.other_lights_stop_mins.state|round(0)|string|length == 1 %} {% set time = time|string + '0' %} {% endif %}
        {% set time = time|string + states.input_number.other_lights_stop_mins.state|round(0)|string %}
        {{ time }}

    teenage_lights:
      friendly_name: 'Lampor släcka tonåringar'
      value_template: >-
        {% if states.input_number.teenage_lights_stop_hour.state|round(0)|string|length == 1 %} {% set time2 = 0 %} {% endif %}
        {% set time2 = time2|string + states.input_number.teenage_lights_stop_hour.state|round(0)|string + ':' %}
        {% if states.input_number.teenage_lights_stop_mins.state|round(0)|string|length == 1 %} {% set time2 = time2|string + '0' %} {% endif %}
        {% set time2 = time2|string + states.input_number.teenage_lights_stop_mins.state|round(0)|string %}
        {{ time2 }}

    kids_lights:
      friendly_name: 'Lampor släcka barn'
      value_template: >-
        {% if states.input_number.kids_lights_stop_hour.state|round(0)|string|length == 1 %} {% set time3 = 0 %} {% endif %}
        {% set time3 = time3|string + states.input_number.kids_lights_stop_hour.state|round(0)|string + ':' %}
        {% if states.input_number.kids_lights_stop_mins.state|round(0)|string|length == 1 %} {% set time3 = time3|string + '0' %} {% endif %}
        {% set time3 = time3|string + states.input_number.kids_lights_stop_mins.state|round(0)|string %}
        {{ time3 }}