- alias: "Låsa groventre"
  initial_state: true
  trigger:
    - platform: state
      entity_id: lock.groventre
      to: 'unlocked'
  condition:
    - condition: state
      entity_id: binary_sensor.window_door_sensor
      state: 'off'
  action:
    - delay:
        minutes: "2"
    - service: lock.lock
      data:
        entity_id: lock.groventre
        code: !secret verisure_code
