- alias: "Lampor på"
  initial_state: true
  trigger:
   - platform: sun
     event: sunset
     offset: '-01:30:00'
  condition:
    condition: time
    before: '18:00'
  action:
    - service: homeassistant.turn_on
      entity_id: group.window_lights


- alias: "Lampor av övrigt"
  initial_state: true
  trigger:
    platform: template
    value_template: '{{ states.sensor.other_lights.state == states.sensor.time.state }}'
  action:
    - service: homeassistant.turn_off
      entity_id: group.other_lights


- alias: "Lampor av tonåringar"
  initial_state: true
  trigger:
    platform: template
    value_template: '{{ states.sensor.teenage_lights.state == states.sensor.time.state }}'
  action:
    - service: homeassistant.turn_off
      entity_id: group.teenage_lights


- alias: "Lampor av barn"
  initial_state: true
  trigger:
    platform: template
    value_template: '{{ states.sensor.kids_lights.state == states.sensor.time.state }}'
  action:
    - service: homeassistant.turn_off
      entity_id: group.kids_lights