- alias: "Lampor på"
  initial_state: true
  trigger:
   - platform: sun
        event: sunset
        offset: '-01:30:00'
  action:
    - service: homeassistant.turn_on
      entity_id: group.window_lights


- alias: "Lampor tonåringar av vardagar"
  initial_state: true
  trigger:
    - platform: time
      at: '21:30:00'
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    - service: homeassistant.turn_off
      entity_id: group.teenage_lights


- alias: "Lampor tonåringar av helger"
  initial_state: true
  trigger:
    - platform: time
      at: '23:00:00'
  condition:
    condition: time
    weekday:
      - sat
      - sun
  action:
    - service: homeassistant.turn_off
      entity_id: group.teenage_lights


- alias: "Lampor barn av vardagar"
  initial_state: true
  trigger:
    - platform: time
      at: '20:00:00'
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    - service: homeassistant.turn_off
      entity_id: switch.ellen


- alias: "Lampor barn av vardagar"
  initial_state: true
  trigger:
    - platform: time
      at: '21:00:00'
  condition:
    condition: time
    weekday:
      - sat
      - sun
  action:
    - service: homeassistant.turn_off
      entity_id: switch.ellen

    

- alias: "Lampor vuxna av vardagar"
  initial_state: true
  trigger:
    - platform: time
      at: '23:00:00'
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    - service: homeassistant.turn_off
      entity_id: group.other_lights


- alias: "Lampor vuxna av helger"
  initial_state: true
  trigger:
    - platform: time
      at: '23:59:00'
  condition:
    condition: time
    weekday:
      - sat
      - sun
  action:
    - service: homeassistant.turn_off
      entity_id: group.other_lights