group:
  alarm_devices_sensors:
    name: Alarm devices
    entities:
      - binary_sensor.openclose_27
      - binary_sensor.openclose_28
      - binary_sensor.openclose_24
      - binary_sensor.window_door_sensor
      - binary_sensor.garageporten


automation:
  - id: alarm
    alias: "Send alarms"
    initial_state: true
    trigger:
      - platform: state
        entity_id: device_tracker.micke_iphone7_2
        to: 'not_home'
    condition:
      - condition: state
        entity_id: group.alarm_devices_sensors
        state: 'on'
    action:
      - service: notify.pushbullet
        data:
          message: 'Kolla dörrarna/garaget'
          title: 'Alarm'


automation:
  - id: reminder-ovirt
    alias: "Ovirt alarm"
    initial_state: true
    trigger:
      - platform: state
        entity_id: sensor.ovirt
        to: 'warning'
    action:
      service: notify.pushbullet
      data:
        message: 'Deboliar fungerar inte!'
        title: 'Error'


automation:
  - id: reminder-garage
    alias: "Garage reminder"
    initial_state: false
    trigger:
      - platform: state
        entity_id: binary_sensor.garageporten
        to: 'on'
        for:
          minutes: 20
    action:
      service: notify.pushbullet
      data:
        message: 'Glöm inte stänga porten!!'
        title: 'Garaget'


alert:
  garage_door:
    name: Garage is open
    done_message: Garage is closed
    entity_id: binary_sensor.garageporten
    state: 'on'
    repeat: 30
    can_acknowledge: true
    skip_first: true
    notifiers:
      - pushbullet